### PR TITLE
Update to angular eight

### PR DESCRIPTION
**Pull request by nephi5**
If you are interested in having the project upgraded to the most recent angular version I have done some initial work here. It might make more sense to create a branch called maybe angular-v-8 so that master stays true with the source material and developers who want to develop with the newest version can just the corresponding branch. I have done the migration only with the website folder so far. If you like those changes I'm more happy to migrate the rest of the chapters.

### CODE REVIEW

**Comment by nephi5** [comment]
In order to avoid draining your ci resources will continue the ci checks on my end and create a new pull request once all the ci checks are passing

**Comment by jesselpalmer** [comment]
Hey @nephi5! Thank you so much for opening the PR. I would hold off on updating the project until we update the book with the latest version of Angular so that the book and project will be in sync. I really appreciate you doing this though!

**Comment by nephi5** [comment]
Hi @jesselpalmer, thanks for taking your time to repsond. I would love to help and contribute to updating the source material. Sorry about my other pull request I just your comment now.

**Comment by eliasab16** [comment]
Hello @jesselpalmer, can you at least update the ReadMe to explain how to set up the environment for the project to run? Because right now, the project is impossible to run, and so you can't really read the book. I spent an entire day trying to update all of the dependencies and changing the deprecated declaratoins, but to no avail.

**Pull request closed without merging**
